### ISSUE TITLE
Standardize pipeable Do & APIs across packages

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/data#254]
At the moment we use various names such as `bindValue` vs `let` and names like `andThenBind` that means nothing. We should settle on a set of functions for the pipeable do notation that every module exports.

Also there are some mis-categorized and inconsistent names such as https://effect-ts.github.io/data/modules/Either.ts.html#appendelement that is/should/was called `zipFlatten` in effect

cc @gcanti @IMax153

**Comment by IMax153** [comment]
My suggestion for pipeable `Do` notation would be to trash the idea of a "do" simulation entirely and instead think of our current `Do` simulation as "building up" an object structure:

```ts
pipe(
  Effect.emptyObject(),
  Effect.addProperty("key", () => "value"),
  Effect.addPropertyEffect("anotherKey", () => Effect.succeed("anotherValue")),
  Effect.flatMap(({ key, anotherKey }) => ...)
)
```

**Comment by jessekelly881** [comment]
I prefer set over with as, being a verb, it makes it clear the the object is being updated. I also dislike appending the object name to the end as it would require the name to change for each module whereas `flat` is clear and consistent across object types. Also, I dislike the name empty because it clashes with the empty value of a Monad. What about setProp, setPropFlat, emptyObject?

**Comment by jessekelly881** [comment]
I prefer set over with as, being a verb, it makes it clear the the object is being updated. I also dislike appending the object name to the end as it would require the name to change for each module whereas `flat` is clear and consistent across object types. Also, I dislike the name empty because it clashes with the empty value of a Monad. What about setProp, setPropFlat, emptyObject?

**Comment by jessekelly881** [comment]
Yeah, mapFlat is a much better name than flatMap. Subjectively, I really dislike having to repeat the name of the module when it is already namespaced. The Effect module should already "know" that I'm working with an Effect, so having to write Effect. serviceWithEffect seems like bad form. When working with a library I want to be able to understand a limited set of functions that are overloaded per module and that "know" what they should do with the respective data type without having to tell it that I'm using that data type. I don't want to know that I want to flatMap something and then have to go looking for the name of flatMap in this particular module. I'm exaggerating a bit, but it does take a bit of mental energy vs using the same name across all modules.

**Comment by mikearnaldi** [comment]
I agree, historically the name `M` was appended so `serviceWith` + `serviceWithEffect` was called `serviceWithM` but in different modules you may have multiple `serviceWithEffect`, `serviceWithStream`, etc.

In case of `map` you could imagine that in the Effect module it would be natural to have `map`, `mapOption`, `mapEither`, `mapEffect`. The logical name to remember is `map` and the rest is provided by the LSP in auto-complete

**Comment by jessekelly881** [comment]
Hmm. What if we circumvent the need for the Flat modifier entirely and just assume that setProp assigns a wrapped value. The math functions, for example, take two Eithers and apply the operation to the value(e.g. `Either.sum :: Either e number -> Either e number -> Either e number`) what if we just do the same with the object modifiers. I.e. `Either.setProp :: Either a object -> E a object -> E a object`

```js
pipe(
    E.object(),
    E.setProp("a", () => E.right("a")), 
)
```

**Comment by jessekelly881** [comment]
So, translating from the current Do notation:

```js
pipe(
    E.right(1), 
    E.bindTo("a"), 
    E.andThenBind("b", E.right("b")),
    E.let("c", ({ a, b }) => [a, b])
)
```

would become 

```js
pipe(
    E.right(1), 
    E.asProp("a"), 
    E.setProp("b", () => E.right("b")),
    E.map(obj => ({ ...obj, c:[obj.a, obj.b] }))
)
```

**Comment by mikearnaldi** [comment]
```ts
pipe(
  E.right(1),
  E.asProp("a"),
  E.setProp("b", ({a}) => a + 10),
  E.setPropEither("c", ({b}) => E.right(b + 20))
)
```

**Comment by jessekelly881** [comment]
Do you prefer having 

```js
E.setProp("b", ({a}) => a + 10),
E.setPropEither("c", ({b}) => E.right(b + 20))
```
vs 
```js
E.setProp("b", ({a}) => E.right(a + 10)),
```
I think both are valid approaches.

**Comment by jessekelly881** [comment]
As a side note, I think zipFlatten is a terrible name. jaja. It's extremely unclear by the name alone what it actually does. On the other hand it's very clear what appendElement does.

**Comment by mikearnaldi** [comment]
> Do you prefer having both
> 
> ```js
> E.setProp("b", ({a}) => a + 10),
> E.setPropEither("c", ({b}) => E.right(b + 20))
> ```
> 
> vs just
> 
> ```js
> E.setProp("b", ({a}) => E.right(a + 10)),
> ```
> 
> I prefer the second but I think both are valid approaches. The second one is a little bit more syntax(having to call E.right) in the cases where you want to just assign a regular value but I would guess that that use case is rare and the second option simplifies the api slightly and removes the need for the "flat" instances. It's also a bit more consistent with the other inner-value operators like the math fns that only operate on wrapped values.

I would prefer the first because it's a standard across `effect` that `fn` is the plain equivalent of the monadic `fnModuleName` so it's consistent and I find it many times useful not to have to wrap always Either / Effect and co

**Comment by mikearnaldi** [comment]
> Also, as a side note, I think zipFlatten is a terrible name. jaja. It's extremely unclear by the name alone what it actually does. On the other hand it's very clear what appendElement does.

yes zipFlatten is horrendous :)

**Comment by enricopolanski** [comment]
I too prefer `setProp` alone.

**Comment by jessekelly881** [comment]
setProp alone seems better. Using

```js
import * as S from "@effect/data/Struct"
E.map(S.setProp("a", () => 1)) 
```

can be used to set the prop in the case where the value is unwrapped. 


Are there any benefits to using Do vs just building up the object?

**Comment by mikearnaldi** [comment]
```ts
E.setProp("a", () => 1)
```

is better compared to:

```ts
E.map(S.setProp("a", () => 1)) 
```

From a DX standpoint there is no discussion, if this is the logic I'd argue `setProp` is completely useless as the user can use the spread operator

**Comment by jessekelly881** [comment]
I completely agree. The first is better. But.. setProp alone is better from a DX perspective than setPropEffect. The question is, what DX do we optimize for, the wrapped case or the unwrapped case. If we could override the setProp fn to accept both a wrapped and unwrapped value that would probably be ideal.

**Comment by mikearnaldi** [comment]
It's impossible because you may want to assign an effect to a binding. Having a rich set of consistent api is definately an objective of effect, check how many variants we have in https://effect-ts.github.io/io/modules/Effect.ts.html reducing the functions for the purpose of having less just leads to worse dx

**Comment by jessekelly881** [comment]
Makes sense. We will probably want to have asProp and asPropEffect as well which means we are just renaming the current api. Which is fine, the new names are a lot clearer.

**Comment by mikearnaldi** [comment]
After some internal discussion between core team we decided to keep the naming of Do on the ground that:

- every proposed renaming is longer 
- if one is not familiar with Do they will most likely jump straight into `gen`
- do-bind-let are a simulation of Do and constructing an object is the workaround, their primary objective isn't to build an object rather to represent a sequence of computations that can be dependent on the prior n steps
- if one is familiar with do constructs from other languages the proposed names will only be confusing 

Thanks all for feedback and proposals, I will be closing the issue.
