### ISSUE TITLE
Port `flow` from fp-ts

### ISSUE THREAD

**Issue by vecerek** [Effect-TS/data#429]
I've recently experienced the lack of `flow` in Effect:

```ts
import { pipe } from "effect";
const double = (x: number): number => x * 2;
const add = (x: number) => (y: number): number => x + y;

pipe(
  Effect.succeed(20),
  // instead of: Effect.map(flow(double, add(2)))
  Effect.map((n) => pipe(n, double, add(2)),
  Effect.runSync
)
// 42
```

May I copy it over from `fp-ts`, please? 🙏 😄

**Comment by gcanti** [comment]
@vecerek `flow` was removed in [v0.13.0](https://github.com/Effect-TS/data/blob/main/CHANGELOG.md#0130).

Here's the related [Discord discussion](https://discord.com/channels/795981131316985866/1080904799857418430/threads/1126605364297744385).

**Comment by gcanti** [comment]
Closed by https://github.com/Effect-TS/data/pull/430
