### ISSUE TITLE
Add base64 and base64url and hex encoding & decoding

### ISSUE THREAD

**Issue by fubhy** [Effect-TS/data#469]
I believe the effect ecosystem would benefit from built-in base64 and base64url encoding & decoding utils.

### Status quo

The relationship status of the web platform and base64 can only be described as "it's complicated".

Most browsers natively provide two JavaScript functions for decoding and encoding Base64 *strings*(!): `btoa` (Binary to ASCII) and `atob` (ASCII to Binary). Notably, these [are both *not* part of the ECMAScript spec](https://html.spec.whatwg.org/multipage/webappapis.html#atob),

> From  https://developer.mozilla.org/en-US/docs/Glossary/Base64
> 
> [...] btoa and atob were added to the web platform before it supported binary data types. As a result, the two functions use strings to represent binary data, with the code point of each character representing the value of each byte. This has led to a common misconception that btoa can be used to encode arbitrary text data [...]
> 
> However, the byte-to-code-point correspondence only reliably holds true for code points up to 0x7f. Furthermore, code points over 0xff will cause btoa to throw an error due to exceeding the maximum value for 1 byte.

Both, `btoa` and `atob`, were also [added in Node.js v16 but immediately flagged as deprecated](https://nodejs.org/dist/latest-v16.x/docs/api/globals.html#atobdata) (Stability 3; Legacy). The Node.js documentation continues to recommend the good old `Buffer` APIs for base64 encoding & decoding.

There is currently a [Stage 2 ECMAScript Proposal](https://tc39.es/proposal-arraybuffer-base64/) to add base64 & hex encoding & decoding. 

### Recommended approach

I suggest we implement a base64, a base64url and a hex module and expose full encoding & decoding implementations without attempting to fall back to native `Buffer` or `atob` / `btoa` APIs. This guarantees cross platform functionality & reproducability until the TC39 base64 proposal is implemented. We can use the [Deno implementation](https://github.com/denoland/deno_std/blob/main/encoding/base64.ts) as a blueprint which itself is inspired by an [implementation by Egor Nepomnyaschih](https://gist.github.com/enepomnyaschih/54c437997f8202871278d0fdf68148ca).

I'm going to run some benchmarks to compare performance between `atob`, `btoa`, `Buffer` and the implementations mentioned above.

### Reference

- https://developer.mozilla.org/en-US/docs/Glossary/Base64
- https://html.spec.whatwg.org/multipage/webappapis.html#atob
- https://nodejs.org/dist/latest-v16.x/docs/api/globals.html#atobdata
- https://github.com/nodejs/node/blob/982e7a65cc68b45a0cfe45e2d7c895276501eba1/lib/buffer.js#L1259-L1354
- https://github.com/tc39/proposal-arraybuffer-base64
- https://deno.land/std@0.198.0/encoding

**Comment by roman-koshchei** [comment]
For future, I think Effect ecosystem will also benefit from:
- jwt encoding/decoding
- hashing (for password purposes)

**Comment by tim-smart** [comment]
> For future, I think Effect ecosystem will also benefit from:
> 
> * jwt encoding/decoding
> * hashing (for password purposes)

Hashing will be addressed in a crypto module in /platform.
