### ISSUE TITLE
Migration plan / roadmap from fp-ts

### ISSUE THREAD

**Issue by florianbepunkt** [Effect-TS/data#487]
Is there any roadmap / migration plan from fp-ts? As I understand, you want to merge fp-ts and effect-ts (great!). I would be interested if the These module from fp-ts will make it into this library?

**Comment by steida** [comment]
fp-ts 3 was already incorporated into Effect.

**Comment by florianbepunkt** [comment]
@steida Thank you. `These` exists in fp-ts 3, but I could not find it in effect. Hence my question…

**Comment by steida** [comment]
I would ask in https://discord.gg/effect-ts

**Comment by gcanti** [comment]
@florianbepunkt we had it for a while, but in the end we decided not to include `These` in the `@effect/data` package
