### ISSUE TITLE
Specification for the `toJSON` and `toString` Methods of Data Types

### ISSUE THREAD

**Issue by gcanti** [Effect-TS/data#492]
## `toJSON` Method:

The `toJSON` method should provide a JSON representation of the data type. It should include the following fields:

- An `_id` field that contains the name of the module containing the data type.
- A series of fields depending on the data type's characteristics. If the data type is a tagged union (public), it should include the `_tag` field.

### Example:

```json
{
  "_id": "ModuleName",
  "field1": "value1",
  "field2": "value2"
}
```

~~The `toString` method is a simplified representation similar to YAML of what is returned by the `toJSON` method. It aims to provide a human-readable version of the data type.~~

It aims to provide a human-readable version of the data type, it can be obtained using the `JSON.stringify(this.toJSON(), null, 2)`

**Comment by tim-smart** [comment]
I think formatted JSON is more useful for `toString`, something like `JSON.stringify(this.toJSON(), null, 2)`
